### ISSUE TITLE
Related videos text not displayed in latest Chrome

### ISSUE THREAD

**Issue by user234683** [user234683/youtube-local#100]
https://user-images.githubusercontent.com/49244768/137716852-c91c3b49-d3b0-46ae-a008-12b3d16bafa5.png
Reproducible on Chrome 93
Not reproducible on Ungoogled Chromium 80

**Comment by user234683** [comment]
Seems to be because of the overflow rules. For some reason, the text items are being considered as overflowed and so are being hidden.

**Comment by ByJumperX4** [comment]
Any progress ? Youtube local is still kinda horrible on every chromium-based browser on latest git
