### ISSUE TITLE
Local network server 

### ISSUE THREAD

**Issue by YoshiKill** [user234683/youtube-local#104]
Hello. Any way to make local network YT server in some machines to connect from another? 
I have some old pc on windows xp but YT local dont work on it, if i can host some local yt server on other machine it will be great.

**Comment by bsun0000** [comment]
Locate your ~/.youtube-local/settings.txt and change 
allow_foreign_addresses = False
allow_foreign_post_requests = False
To True.

**Comment by YoshiKill** [comment]
> Locate your ~/.youtube-local/settings.txt and change allow_foreign_addresses = False allow_foreign_post_requests = False To True.

wow, thanks a lot. Its Alive!! Full working. 
з.ы Спасибо! Оно работает :3

**Comment by T0MuX** [comment]
Hi, this solution doesnt work for me. youtube-local is ran on ArchlinuxARM, and works fine on localhost. But not at all from another machine on the same network. And there is no firewall on my ArchlinuxARM machine.

**Comment by bsun0000** [comment]
Double check that you actually change the variables i mentioned before and you did it while program is not running.
If you still cannot connect to your ARM server, open server.py file, find this section of code (near the bottom):

if __name__ == '__main__':
    if settings.allow_foreign_addresses:
        server = WSGIServer(('0.0.0.0', settings.port_number), site_dispatch,
                            log=FilteredRequestLog())

And change 0.0.0.0 to the actual ip address of your machine.

**Comment by user234683** [comment]
You also need to restart youtube-local before settings from settings.txt will take effect

**Comment by T0MuX** [comment]
Hi @bsun0000 this is still not working with this solution. By the way, I dont understand why it should, because "0.0.0.0" already means "any".

@user234683 yes of course, I did.

**Comment by T0MuX** [comment]
Hi again, so this is now solved. I just had misunderstood / misread on the file I had to modify (settings.txt and not settings.py). Sorry guys  ! Thank you for your help  !
