### ISSUE TITLE
Videos are slow to play again

### ISSUE THREAD

**Issue by DUOLabs333** [user234683/youtube-local#107]
The problem where videos take a long time to load is back.

**Comment by user234683** [comment]
Not seeing it on my end. What quality/video shows the issue?

**Comment by DUOLabs333** [comment]
Any video would do (720p default for me).

**Comment by user234683** [comment]
Is there a difference between having the setting Prefer Integrated Sources enabled or disabled?

**Comment by DUOLabs333** [comment]
Oh, it seems to be due to my proxy -- turning it off works. This is an issue I've been having with mitmproxy for a while on various sites, and I opened up an issue with them.
