### ISSUE TITLE
Support Windows XP, Vista, and 7

### ISSUE THREAD

**Issue by user234683** [user234683/youtube-local#110]
The [official windows builds](https://www.python.org/downloads/windows/) for Python are dropping support for Windows 7, and they are no longer providing binaries for the long term support releases which do support it. Continuing to use the 3.7.9 release and getting behind on security patches isn't sustainable.

This will require compiling the [embedded distribution](https://docs.python.org/3/using/windows.html#the-embeddable-package) ourselves.
Two issues:
- CPython requires Visual Studio 2015 to compile, so cannot be done on Linux, which is annoying. I see [these methods](https://stackoverflow.com/questions/6649606/how-to-support-both-vcxproj-to-cmake-on-a-project) for converting vcxproj files to cmake files, but do not know if it is actually reliable.
- I can not find their build script or any documentation about how to build the embedded distribution. [The build instructions](https://github.com/python/cpython/blob/main/PCbuild/readme.txt) don't seem to mention it.

Related: #6, #104

**Comment by bsun0000** [comment]
Install some (server) linux distro on a virtual machine and use it this way. 256Mb of RAM and 1-10% of a single cpu core is a small price to pay to ignore all windows-related shit.

**Comment by user234683** [comment]
Closing this in favor of continuing to use a separate release for old versions of windows with Python 3.7.9, as those old versions aren't supported by security patches in general anyways
