### ISSUE TITLE
Livestreams don't work in VLC.

### ISSUE THREAD

**Issue by DUOLabs333** [user234683/youtube-local#114]
Example: `https://youtube.test/https://www.youtube.com/watch?v=Fgo5ra5PxJk`. I get a URL to an m3u8. I paste it in VLC, nothing loads.

**Comment by user234683** [comment]
Working on my end with vlc 3.0.12 on debian @ 360p and 480p. It takes about 13 seconds to load. Perhaps there is a regression with the latest vlc version?

**Comment by DUOLabs333** [comment]
I would try, but I can't go back because Arch Linux ARM doesn't have a rollback mechanism (it does, but it only started November 2021).

**Comment by user234683** [comment]
I tested it with vlc 3.0.16 on Windows with [this livestream](https://www.youtube.com/watch?v=5qap5aO4i9A) and it works. If it is a vlc issue, it must be specific to the latest linux version. Have you tried checking the VLC error log in verbose mode?

**Comment by DUOLabs333** [comment]
I found this error: `adaptive demux error: Failed to create demuxer (nil) Unknown`
