### ISSUE TITLE
plyr and doubleclick for fullscreen

### ISSUE THREAD

**Issue by zrose584** [user234683/youtube-local#117]
Why is it [disabled](https://github.com/user234683/youtube-local/blob/932fde4c6925ab9dcd89573cf8c09c9b186f3434/youtube/static/js/plyr-start.js#L122)? Maybe make it a setting?

**Comment by user234683** [comment]
When pausing and unpausing a video (such as when trying to pause on a certain moment of interest), fullscreen frequently is activated unintentionally. A setting is fine, but only if anyone wants/uses the feature
