### ISSUE TITLE
Tor exit nodes being blocked more aggressively

### ISSUE THREAD

**Issue by user234683** [user234683/youtube-local#121]
This is the source of the now-fixed max redirect errors. YouTube is redirecting to the google.com/sorry page. It takes a large number of circuit changes before getting an exit node that works. However, some types of requests seem unaffected, such as the requests for comments, and if I recall correctly, android user-agent requests for the player.

Worth looking into whether spoofing the android client for everything can get around this. I don't have time to work on it much so any results/insights/pull requests are welcome

**Comment by ByJumperX4** [comment]
We could also implement lokinet as an alternative to tor to anonymize traffic

**Comment by user234683** [comment]
As of 1/20/2024, Tor routing appears to work without this problem. Usage of the android client might have fixed this.
