### ISSUE TITLE
Some kind of recommendations appearing

### ISSUE THREAD

**Issue by ByJumperX4** [user234683/youtube-local#123]
Hi, I've been using youtube-local everyday for quite some time, and i've seen recommendations that seems based on my subscriptions (videos from youtube channels i'm subscribed to - only in youtube-local, so locall - being recommended on videos that have nothing in common), does youtube-local have any feature like that ? If yes, is it possible to disable that ? Or should I instead worry about setting up some way to anonymize my network traffic ?

**Comment by user234683** [comment]
Do you have Tor routing enabled?

**Comment by ByJumperX4** [comment]
Nope, I'm going to enable it to see if those stay there

**Comment by ByJumperX4** [comment]
After a week of testing, it seems to be fine with tor routing enabled, that's still scary to see appearing without it

**Comment by user234683** [comment]
I've noticed in the past even before using youtube-local that YouTube will make recommendations based on IP address, and even seems to cross-correlate different IPs/browsers if it thinks it's the same person. So it's not too surprising to see it happen; definitely a useful test case to demonstrate the value of Tor routing, however.
