### ISSUE TITLE
[Feature] "Play all" for a channel's videos

### ISSUE THREAD

**Issue by DUOLabs333** [user234683/youtube-local#125]
Maybe a button for playing all of a channel's videos as a playlist?

**Comment by user234683** [comment]
Temporary workaround: take the url `https://www.youtube.com/playlist?list=UU` and put the channel ID after it without the UC part.
e.g. `UCoxcjq-8xIDTYp3uz647V5A` -> oxcjq-8xIDTYp3uz647V5A -> https://www.youtube.com/playlist?list=UUoxcjq-8xIDTYp3uz647V5A`

**Comment by DUOLabs333** [comment]
I tried that on youtube-local, but got a completely different playlist with videos by completely different uploaders.

**Comment by DUOLabs333** [comment]
However, for some reason, the playlist isn't played in order.

**Comment by DUOLabs333** [comment]
https://youtube.test/https://www.youtube.com/playlist?list=UU6Ii2PPnHDkjLTJJQgOw7sQ

**Comment by DUOLabs333** [comment]
I found the problem --- Once you get to the third page, the playlist view scrolls exactly `n` videos ahead, if the video is `n` videos down on the playlist view page. For example, if `https://youtube.test/https://www.youtube.com/watch?v=09Li7FyJUfc&list=UU6Ii2PPnHDkjLTJJQgOw7sQ&index=24` is `4` videos down on `https://youtube.test/https://www.youtube.com/playlist?list=UU6Ii2PPnHDkjLTJJQgOw7sQ&index=49&page=2`, and when you click on it, the playlist view on the right side starts at the video 4 videos down.

![image](https://user-images.githubusercontent.com/49244768/160108037-87b4b042-4897-46cb-9ba8-c10c0f495708.png)

**Comment by DUOLabs333** [comment]
The `n` also increments if you go to the next page; so if you go to page 3, the playlist is scrolled `21` videos ahead. A way to fix this is for the playlist view to start from video `floor(index/20)`

**Comment by DUOLabs333** [comment]
The problem is that `youtube-local` is just a view for youtube, and youtube only keeps the last `100` videos.

**Comment by DUOLabs333** [comment]
Autoplay also jumps down a certain number of videos (I can't figure out how it works, though)
