### ISSUE TITLE
UI needs tweaks , pls fix these 

### ISSUE THREAD

**Issue by ghost** [user234683/youtube-local#140]
Problems

- title for playlist videos is absent(when a video is playing) , pls fix this
- no button/keyboard shortcut for NEXT VIDEO in a playlist , pls fix this
- show quality switch button (next to speed button )even with plyr

**Comment by user234683** [comment]
> title for playlist videos is absent(when a video is playing) , pls fix this
Are you referring to issue #100 for Chrome? Just fixed

> no button/keyboard shortcut for NEXT VIDEO in a playlist , pls fix this
Recommend opening a separate issue. @zrose584 might be interested in this feature

> show quality switch button (next to speed button )even with plyr
Please explain more

**Comment by SiddharthSharma16923** [comment]
![image](https://user-images.githubusercontent.com/75392515/178092667-bc75a6e9-6455-4a6c-9143-7abdd425f2ec.png)

> meh
