### ISSUE TITLE
OSError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions 

### ISSUE THREAD

**Issue by fatalnyl** [user234683/youtube-local#141]
This is for people using Windows 10. Some of you might encounter this problem. This happened because port 8080 that youtube-local using is used by other services. Here is how I solved it.

1. open powershell. 
2. enter `netstat -na` , find the row with port :8080 
3. find the app's PID
4. go to task manager, details tab, find the corresponding PID and end the task
5. to prevent it again, right click on the app and go to services, disable it from auto starting.

**Comment by user234683** [comment]
Is this an inbuilt service using the port? Or a relatively common app? Might be worth changing the default port in those cases
