### ISSUE TITLE
Autoplay

### ISSUE THREAD

**Issue by canjbfeeltheesemuffins** [user234683/youtube-local#143]
Can you make the video auto play without clicking on the play icon?

**Comment by canjbfeeltheesemuffins** [comment]
yo thanks for this whole thing btw

**Comment by canjbfeeltheesemuffins** [comment]
nvm I just had to add autoplay

**Comment by khlsvr** [comment]
What do you mean "add autoplay"? Where and how do I add it?

**Comment by s4m13337** [comment]
How is this done? I am also looking for this.

**Comment by user234683** [comment]
@khlsvr @s4m13337 
I Just added a setting to do this, will be included in the next release tomorrow
