### ISSUE TITLE
I made an AUR package for youtube-local

### ISSUE THREAD

**Issue by ByJumperX4** [user234683/youtube-local#145]
Hi user234683 (and everyone that contributed too), thanks for this awesome project. I've been using it for over a year and a half now and it's awesome.

Today I made an Arch Linux package distributing it, so Arch Linux users can install it easily.
I provided my own systemd service to be able to run it as user, use `systemctl --user enable --now youtube-local` to enable it.

It's available right here: https://aur.archlinux.org/packages/youtube-local-git

Hope Arch users will enjoy it 😁

**Comment by user234683** [comment]
Thank you! This is great

**Comment by ByJumperX4** [comment]
I'm gonna close this because it's not really an issue and it's mentionned on the readme now
