### ISSUE TITLE
Missing the "live" page in youtube channels.

### ISSUE THREAD

**Issue by khlsvr** [user234683/youtube-local#152]
Quite often I like to check if some of the channels regularly doing livestreams are currently live but I can't find out how I can do that with youtube-local. For example the channel https://www.youtube.com/c/nihonkiin_ch has the subpage for livestreams at https://www.youtube.com/c/nihonkiin_ch/streams but with youtube-local it doesn't exist. 

If I know the URL to a currently playing livestream, the youtube-local gives me direct URLs to livestreams in different quality as I guess it doesn't support playing the livestreams in the embedded player itself but this is fine by me.

**Comment by user234683** [comment]
Fixed in PR #170
