### ISSUE TITLE
[Question] Ranking?

### ISSUE THREAD

**Issue by God-damnit-all** [user234683/youtube-local#154]
It's not made clear anywhere whether a higher ranking or a lower ranking gets priority.

The default setting is H264 `#1`, VP9 `#2`, AV1 `#3`. Assuming integrated sources aren't used, which is played?

**Comment by user234683** [comment]
#1 gets highest priority, so H264 gets played. If two sources have
equal priority numbers, then the one with the smaller file size gets
played
