### ISSUE TITLE
Error: Error getting missing player or bypassing age-restriction: This video is unavailable

### ISSUE THREAD

**Issue by uberblarr** [user234683/youtube-local#165]
After refreshing the page 1-3 times the error is gone.

**Comment by quetzalsly** [comment]
same problem here! refreshing a few times makes it work again

**Comment by user234683** [comment]
@stl3 That line of code shouldn't activate unless you enabled the `gather_googlevideo_domains` hidden setting. I recommend disabling that

**Comment by stl3** [comment]
> @stl3 That line of code shouldn't activate unless you enabled the `gather_googlevideo_domains` hidden setting. I recommend disabling that

Didn't even realise I still had that on lol, nice catch thanks!
