### ISSUE TITLE
Error: Error getting missing player or bypassing age-restriction: This video is unavailable

### ISSUE THREAD

**Issue by ksawerek** [user234683/youtube-local#169]
Used to work after refreshing a few times

**Comment by hDmtP** [comment]
> Used to work after refreshing a few times

Well now the videos aren't loading anymore.

Btw I'm using this one : https://git.sr.ht/~heckyel/yt-local

**Comment by user234683** [comment]
Duplicate of #165 
However, the fix for that issue has its own major issue, being discussed in #168

**Comment by user234683** [comment]
All fixed in latest release
