### ISSUE TITLE
features and suggestions ! cant have enough of them

### ISSUE THREAD

**Issue by ghost** [user234683/youtube-local#173]
1. consolas font ( but i love it ) 
3. remove download options : who needs it? ( think realistically) , if i was to set out to download videos , i would use something like snaptube ( faster to batch download music or videos ) , or use mediahuman youtube downloader ( supports copy url detect , drag , drop; tip: its the best out there 
i have tested all of em and i just gave you the result of my long painful journey of testing each malicious youtube downloader
🙌
5. make the header's background white ( black is ugly ), try taking inspiration from the vanilla youtube
6. also replace the like/dislike count by a percentage instead ( the dislike count does one thing : tells me "is this video hated or not? , a percentage does that same thing in a better way ) , if dislikes ever come back to youtube
8. anti click bait - thumbnails from inside the video
10. put the donate button on top left ( lol it doesnt even exits , now , so put it somewhere )
11. use empty space on settings page for donation request ( why not? )

**Comment by fcjtd** [comment]
THE CHANNELS TAB , where is it?

**Comment by smithed** [comment]
your very first suggestion is to remove a feature because you prefer a different tool? wow.

**Comment by user234683** [comment]
Number 5 is theoretically possible by querying the video-hover previews, but this would add a lot of network requests (e.g. viewing the channel page would need to send out 30 requests), making it impractical.

The channels tab is a good request, being tracked in #132 

Other ones are too minor to be worth the extra technical complexity. Some of these, like the font, you can achieve on your local copy using pretty easy modifications of the code
