### ISSUE TITLE
Failed to connect to tor

### ISSUE THREAD

**Issue by ghostlyentity** [user234683/youtube-local#174]
greetings, i have recently installed version 2.8.1
almost everything is working fine so far, only when i click on any subscribed channel i get this error

"Failed to connect to Tor. Check that Tor is open and that your internet connection is working.

SOCKSHTTPSConnectionPool(host='m.youtube.com', port=443): Max retries exceeded with url: /playlist?list=UUOkhTr4FqEAWRz2UecVsh4g&pbj=1 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7fb796778350>: Failed to establish a new connection: [Errno 111] Connection refused'))"

(apologies for a lack of screenshot, it doesnt let me currently)

my internet connection is working fine so i am unsure why it refuses a connection

**Comment by user234683** [comment]
- Does this happen for any pages, or just channel pages (I see it's a playlist page in the url)
- Do you have Tor browser open? If not did you mean to enable the Route Tor setting?
