### ISSUE TITLE
The system cannot find the specified path. (Windows)

### ISSUE THREAD

**Issue by Preppyprep** [user234683/youtube-local#177]
When I open the bat file, this is the error it gives me which I mentioned in the title.

**Comment by tvcat** [comment]
Make sure you extracted all files to the same single folder.

**Comment by Preppyprep** [comment]
> Make sure you extracted all files to the same single folder.

I did. It just keeps showing this error. even if i run it on admin

**Comment by user234683** [comment]
Can you post a screenshot of the error as well as a screenshot of the
folder you extracted the program to?

**Comment by Preppyprep** [comment]
![image](https://github.com/user234683/youtube-local/assets/69249209/f645c533-21e7-490e-a0b8-081d9bdd35a5)

I extracted it in Downloads folder

**Comment by tvcat** [comment]
Create a folder under C:\ with a name that without any space. Extract all the zip file contents to that folder and try again.

**Comment by Preppyprep** [comment]
C:\ytlocal>REM  https://stackoverflow.com/a/25719250                                                                                                                                                                                            C:\ytlocal>REM  setlocal makes sure changing directory only applies inside this bat file,                                                                                                                                                       C:\ytlocal>REM  and not in the command shell.                                                                                                                                                                                                   C:\ytlocal>setlocal                                                                                                                                                                                                                             C:\ytlocal>REM  So this bat file can be called from a different working directory.                                                                                                                                                              C:\ytlocal>REM  C:\ytlocal\ is the directory with this bat file.                                                                                                                                                                                C:\ytlocal>cd /d "C:\ytlocal\"                                                                                                                                                                                                                  C:\ytlocal>REM  This is so brotli and gevent search in the python directory for the                                                                                                                                                             C:\ytlocal>REM  visual studio c++ runtime dlls                                                                                                                                                                                                  C:\ytlocal>set PATH=.\python;C:\Python311\Scripts\;C:\Python311\;C:\Program Files\Python312\Scripts\;C:\Program Files\Python312\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\Python312;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Program Files\PuTTY\;C:\Users\porcelain\AppData\Local\Microsoft\WindowsApps;C:\Users\porcelain\AppData\Roaming\npm                                                                                                                                                                         C:\ytlocal>.\python\python.exe -I .\server.py                                                                           The system cannot find the path specified.                                                                                                                                                                                                      C:\ytlocal>echo Press any key to quit...                                                                                Press any key to quit...                                                                                                                                                                                                                        C:\ytlocal>PAUSE  1>nul

**Comment by user234683** [comment]
Please post a screenshot of the folder you extracted it into, showing
its contents

**Comment by user234683** [comment]
The issue is that you're downloading the raw repository source code
using the "Download zip" option on github. Go to the releases page
instead and download the windows release from there
