### ISSUE TITLE
Error message in video: "The following content is not available on this app..."

### ISSUE THREAD

**Issue by metrast** [user234683/youtube-local#205]
I am on macOS and use the latest version of youtube-local 2.8.7 and on some videos i get these messages in the video player:

![Screenshot 2024-03-28 at 15 31 31](https://github.com/user234683/youtube-local/assets/117864304/1092adef-c941-4c54-b2bc-b640b4349ee7)

Some other videos work just fine. 

The specific video I wanted to watch here was this one: https://www.youtube.com/watch?v=2tjcx1rTQio

**Comment by MBCX** [comment]
Yeah. Same here too, though, for your video example it worked fine for me, but others not.

If you reload the video enough times the video eventually starts playing.

**Comment by fislysandi** [comment]
same there, it happens no matter the platform you are on. 

seems like youtube doesnt like that we watch it without loading all this javascript framework bloat.

**Comment by metrast** [comment]
> Yeah. Same here too, though, for your video example it worked fine for me, but others not.
> 
> If you reload the video enough times the video eventually starts playing.

You are right. Reloading eventually fixes it.

**Comment by diegovskytl** [comment]
Same issue here, seems to be platform, browser and location independent.

**Comment by MBCX** [comment]
I've been bug-hunting this issue and *I think* I found a pattern.

At least to me, this error **occurs only with not-seen-before videos**, if you go to a video you already watch, the possibilities of this error occurring its **lower**.

I still don't know **what** is causing this and **where** its happening though.

My hypothesis is that *maybe* this could be related to #203, some out of date values in the code are triggering this.

**Comment by MBCX** [comment]
OK. Nevermind the above.

While debugging the application, the issue *seems* to be in **how the app is extracting the video**. Sometimes (pretty much at random, afaik), the extraction will "fail" and YouTube itself will return the infamous "Video Not Available", which then ends what we see here. So the issue seems rooted in youtube-local is extracting the video.

**Comment by user234683** [comment]
Seemed to find the issue; made a new release. Let me know if it still doesn't work

**Comment by MBCX** [comment]
On my end, it works perfectly! Tested with 10 different videos and went OK

**Comment by MBCX** [comment]
Oh, nevermind, spoke too soon =(.

![image](https://github.com/user234683/youtube-local/assets/63003002/cf3b8e03-732e-4f9e-81ea-575de43b879c)

[Link to video tested](https://www.youtube.com/watch?v=WmIq7mX97j0)

**Comment by ericpa06** [comment]
It's affecting other alternative front-end for youtube as well. Related thread: 

https://github.com/iv-org/invidious/issues/4498

**Comment by user234683** [comment]
Since NewPipe doesn't seem to have the problem (no issue open and that video works), we should copy their extraction method

**Comment by dmbarrad** [comment]
same issue here, I think I might just give up on youtube entirely. this is just too much hustle to fix their own issues, and now they want to force it on us, I think abandonment is the way.

**Comment by user234683** [comment]
https://github.com/yt-dlp/yt-dlp/issues/9554
Here is the yt-dlp issue; I noticed youtube-dl is using the ios client instead. I tested it and that one appears to work. I pushed a new release, let me know if the issue persists

**Comment by user234683** [comment]
> same issue here, I think I might just give up on youtube entirely. this is just too much hustle to fix their own issues, and now they want to force it on us, I think abandonment is the way.

The long term goal of youtube-local has been to support alternative platforms such as LBRY, odysee, vimeo, and rumble to help people migrate away from youtube as much as possible; I just don't have the free time anymore to make it happen

**Comment by astounds** [comment]
> The long term goal of youtube-local has been to support alternative platforms such as LBRY, odysee, vimeo, and rumble to help people migrate away from youtube as much as possible; I just don't have the free time anymore to make it happen

I'm grateful for the work you @user234683  do keeping youtube-local. I also know that the optimal thing is for video producers to migrate to self-hosted platforms like peertube, mediagoblin, etc.

**Comment by sseodate** [comment]
hi @user234683 is this issue fixed ?  i got more report back then!

**Comment by user234683** [comment]
On Mon, 2024-05-06 at 03:22 -0700, sseodate wrote:
> hi @user234683 is this issue fixed ? i got more report back then!
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>

Yes it is fixed

**Comment by sseodate** [comment]
Sorry, as i checked, i am still got error to get mix link (stream video w sound) even i upgraded to latest version.
