### ISSUE TITLE
Error getting mssing player: This video is unavailable

### ISSUE THREAD

**Issue by MBCX** [user234683/youtube-local#221]
In Youtube's war against all other ways of interacting with its service, youtube-local is now in the cross fire and this error appears in every video I try to watch, doesn't matter if you're using a VPN, or TOR, or neither.

![image](https://github.com/user-attachments/assets/aebc2d93-8087-423a-b4ce-0f20fe9e04bb)

If you reload enough times it will eventually get through, but this is still super annoying.

**Comment by MBCX** [comment]
This commit #219 actually seems to fix the issue for me.

**Comment by dmbarrad** [comment]
Got the same issue, Still don't know how does the #219 helps?

**Comment by KongoBongo** [comment]
Yeah, this is still persistent and now it just full on doesn't work. You can spam refresh but it will still come up with the same error message.

**Comment by alive4ever** [comment]
> Got the same issue, Still don't know how does the #219 helps?

The #219 pull request introduces `mweb` innertube client with `n` signature decryption to get working player inside the watch page and several more changes.

The simplest fix is by removing `params` from yt api request body and changing the client to `ios`. Here is how to do it from the `master` branch.

```patch
diff --git a/youtube/watch.py b/youtube/watch.py
index 8cddf1d..b08d29a 100644
--- a/youtube/watch.py
+++ b/youtube/watch.py
@@ -337,7 +337,6 @@ def _add_to_error(info, key, additional_message):
 def fetch_player_response(client, video_id):
     return util.call_youtube_api(client, 'player', {
         'videoId': video_id,
-        'params': 'CgIQBg',
     })
 
 def fetch_watch_page_info(video_id, playlist_id, index):
@@ -367,7 +366,7 @@ def extract_info(video_id, use_invidious, playlist_id=None, index=None):
         gevent.spawn(fetch_watch_page_info, video_id, playlist_id, index),
 
 
-        gevent.spawn(fetch_player_response, 'android-test-suite', video_id)
+        gevent.spawn(fetch_player_response, 'ios', video_id)
     )
     gevent.joinall(tasks)
     util.check_gevent_exceptions(*tasks)
```

**Comment by ntnguyen1234** [comment]
Btw, I think the current `INNERTUBE_CONTEXT` of `ios` doesn't allow 4K 60fps? When I try the config from yt-dlp, I can play 4K 60fps now (example link: `https://www.youtube.com/watch?v=Mw1MWfilz_k`)

https://github.com/yt-dlp/yt-dlp/blob/4b5eec0aaa7c02627f27a386591b735b90e681a8/yt_dlp/extractor/youtube.py#L198-L207

```
'INNERTUBE_CONTEXT': {
    'client': {
        'hl': 'en',
        'gl': 'US',
        'clientName': 'IOS',
        'clientVersion': '19.45.4',
        'deviceMake': 'Apple',
        'deviceModel': 'iPhone16,2',
        'userAgent': 'com.google.ios.youtube/19.45.4 (iPhone16,2; U; CPU iOS 18_1_0 like Mac OS X;)',
        'osName': 'iPhone',
        'osVersion': '18.1.0.22B83',
    }
},
```
