### ISSUE TITLE
external html5 video player

### ISSUE THREAD

**Issue by zrose584** [user234683/youtube-local#25]
The arrow hotkeys don't work correctly, because the native <video> control panel also reacts to them.
Not relying on the native controls would give more freedom, including implementing these hotkeys correctly.
Maybe a timebar (aka scrubber/scrub bar) preview would also be possible..

**Comment by user234683** [comment]
I see what you mean. It seems to be a bug with chrome's video player. I've never been a fan of the way chrome's video player looks/works compared to firefox's, so I'm open to the idea, but I would insist the replacement be lightweight (don't want thousands of lines of javascript).

**Comment by zrose584** [comment]
I don't know if it counts as "lightweight", but I think https://plyr.io/ looks promising.
[plyr](https://github.com/sampotts/plyr/tree/master/src) has ~7kloc.
[video.js](https://github.com/videojs/video.js/tree/main/src) has ~12kloc.
[firefox's videocontrols](https://searchfox.org/mozilla-central/source/toolkit/content/widgets/videocontrols.js) has ~32kloc.

Maybe such an amount of code is just needed for "decent" controls.

Btw, I think both firefox and chromium are "code monsters".. However we usually don't care, because we don't have to deal with the code base. We just *use* it.
It's the same for such an video player. We just *use* their (hopefully stable) API, and that's it.
So even if they'd have 50kloc, I don't see it as too big of a deal.

**Comment by user234683** [comment]
plyr is a good candidate. Another one that might be even smaller is [mediaelement](https://github.com/mediaelement/mediaelement), though I can't figure out if the big flash backend is optional or what. But the controls themselves seem to be implemented in like ~2.2kloc, unless I'm missing some includes somewhere (for comparison, this entire project is about 5.2kloc of python and js). Even if the browser built-ins might be bloated, no reason we can't do better if it's possible. Plus, those built-ins might have special optimizations. Also, the firefox videocontrols looks like only 3.2k, not 32k, unless you're counting something else?

**Comment by zrose584** [comment]
Since video.js is used by both invidious and yotter, also using it would enable higher code reuse. What do you think?

> Also, the firefox videocontrols looks like only 3.2k, not 32k

oops, you are right!
