### ISSUE TITLE
[request] classic youtube theme or something resembling it

### ISSUE THREAD

**Issue by brightersun99** [user234683/youtube-local#27]
Hi, would it be hard to re-create something like or identical to 2008~ youtube UI? 

That would be a great addition to this awesome project.

**Comment by user234683** [comment]
It would be too much extra code complexity and maintenance for an obscure feature. Though you might want to look at the setting to disable theater mode if you haven't seen it. You're always free to make a fork of the project and take it in other directions, of course.
