### ISSUE TITLE
[Request] Add SponsorBlock support

### ISSUE THREAD

**Issue by jmnt9** [user234683/youtube-local#30]
Hello and first let me thank you for making youtube usable again (it became bloated and laggy after they retired the old interface). But, nowadays, certain content creators abuse in the video ads, so i find the sponsorblock extension a must to watch youtube videos.
So, is it possible to implement the sponsorblock ad skipping in the embedded video player?
Kodi has an addon for this, but i don't know how easy it would be to implement in your app:
https://github.com/ajayyy/SponsorBlock/wiki/3rd-Party-Ports#kodi

My current workaround is to use invidious with the sponsorblock extension (which supports invidious instances), but I much prefer your app, because it's much more reliable.
If it's too hard or too much work, thank you very much nonetheless, because it's an excellent tool that made youtube bearable for me (and I'm sure for a lot of other people).

**Comment by zrose584** [comment]
https://git.gir.st/subscriptionfeed.git/blob/59a590d:/app/youtube/templates/watch.html.j2#l28

**Comment by jmnt9** [comment]
Hello and thank you for the reply, but how do I use this? (I'm sorry, but i forgot to tell that I don't have programming skills).

**Comment by zrose584** [comment]
The code I linked fetches the video sequences to skip from `https://sponsor.ajay.app/api/skipSegments/${sha256(video_id)}` and adds a `timeupdate` event for each sequence to skip.
It is basically ready to use, just minor changes would be necessary.

Maybe I will do this later..

**Comment by user234683** [comment]
Another option is to do a pull request on the addon adding the support (so all the features are there such as voting) which may or may not be an obtrusive amount of changes depending on its architecture.

**Comment by zrose584** [comment]
I also see the benefits in adding support to the addon itself. But for now, I think #32 will suffice / be better than nothing.

**Comment by jmnt9** [comment]
Hello again and thank you for all the replies so far.
So, do I need to add or modify something in my current installation or should I wait until it gets integrated in the main program?
In the meantime, I want to thank both of you, for considering my request.

**Comment by user234683** [comment]
Nope, nothing to modify. The feature should be ready in the next release.

**Comment by jmnt9** [comment]
Thank you very much :-)
I hope the app gets more visibility, so you can attract even more devs to improve it and make it even better (for me, it's already miles better than the other options available, so, once again, thank you).

PS:
I want to thank zrose584 personally, for filling my request so quickly (you're awesome).

**Comment by ajayyy** [comment]
Adding support without the colouring on the seekbar would probably just require modifying the url parser. Though, we'd probably have to think of a good way to add this to the "Add Invidious Instance" in the options page without bloating the options page even more. Maybe just renaming that to invidious/youtube-local and using not require the user to choose which one it is.

**Comment by zrose584** [comment]
@ajayyy 
```diff
From 3fc4f7c4af86aa9949f3305a23539968402e1421 Mon Sep 17 00:00:00 2001
From: zrose584 <57181548+zrose584@users.noreply.github.com>
Date: Sun, 18 Oct 2020 22:24:03 +0200
Subject: [PATCH] getYouTubeVideoID() - support youtube-local pathnames

---
 src/content.ts | 15 ++++++---------
 1 file changed, 6 insertions(+), 9 deletions(-)

diff --git a/src/content.ts b/src/content.ts
index a2911f9..d2d084f 100644
--- a/src/content.ts
+++ b/src/content.ts
@@ -800,17 +800,14 @@ function getYouTubeVideoID(url: string) {
     }
 
     //Get ID from searchParam
-    if (urlObject.searchParams.has("v") && ["/watch", "/watch/"].includes(urlObject.pathname) || urlObject.pathname.startsWith("/tv/watch")) {
+    let m = null;
+    if (urlObject.searchParams.has("v") && urlObject.pathname.match(/^\/((youtube\.com\/)?watch\/?$|tv\/watch)/)) {
         let id = urlObject.searchParams.get("v");
         return id.length == 11 ? id : false;
-    } else if (urlObject.pathname.startsWith("/embed/")) {
-        try {
-            return urlObject.pathname.substr(7, 11);
-        } catch (e) {
-            console.error("[SB] Video ID not valid for " + url);
-            return false;
-        }
-    } 
+    }
+    else if (m = urlObject.pathname.match(/(?:embed|youtu.be)\/([^/]{11})/)) {
+        return m[1];
+    }
     return false;
 }
 
-- 
2.20.1
```

**Comment by jmnt9** [comment]
@ajayyy 
Having direct support for youtube-local in SponsorBlock extension would be excellent too (and could mean one less thing the devs have to worry about, in the future, because google likes to break things out of nowhere).

PS:
ajayyy, I also want to thank you for making (a lot of) youtube channels watchable again (the amount of ads in certain youtube channels is just mind blowing. I understand that they need to make money, but, in some channels, is just too much, so thank you very much for doing this).

**Comment by user234683** [comment]
Added in latest release

**Comment by jmnt9** [comment]
> 
> 
> Added in latest release

I want to thank to all involved that made this possible.
I'm going to test it in the next days and will come back to leave a feedback.

PS:
Is this project safe? With all the fuss around youtube-dl I'm a bit worried and I would hate to see this project taken down.

**Comment by user234683** [comment]
> Is this project safe? With all the fuss around youtube-dl I'm a bit worried and I would hate to see this project taken down.

For now, I think it's too small to attract the "Eye of Sauron", but I am thinking about/working on contigency measures, such as periodically archiving all issues into the git repository itself, a legal disclaimer about downloads, etc. I've also checked the codebase to make sure there's no copyrighted urls.

**Comment by jmnt9** [comment]
> 
> 
> > Is this project safe? With all the fuss around youtube-dl I'm a bit worried and I would hate to see this project taken down.
> 
> For now, I think it's too small to attract the "Eye of Sauron", but I am thinking about/working on contigency measures, such as periodically archiving all issues into the git repository itself, a legal disclaimer about downloads, etc. I've also checked the codebase to make sure there's no copyrighted urls.

I hope no Smeagol come by to take "Our Precious". It would be heart shattering.
Yeah, I think that leaving copyrighted links was what, ultimately, caused all the problems for them.
Also, will having youtube in the program's name not bring undesirable attention? Maybe renaming the project to localtube or something similar would put it on a safer side.
BTW, I would like to say that sponsorblock is working great. Thank you again to everyone involved.
