### ISSUE TITLE
Support being embedded as an iframe

### ISSUE THREAD

**Issue by pExeen** [user234683/youtube-local#36]
This would be cool so you could just replace all requests to youtube to youtube-local with an extension like [Redirector](https://addons.mozilla.org/en-US/firefox/addon/redirector/) and still have embedded videos work.

**Comment by zrose584** [comment]
@pExeen 
If you like this feature maybe try to implement it? :)

I wonder what would be better:
* edit the 721 lines long [watch.html](https://github.com/user234683/youtube-local/blob/master/youtube/templates/watch.html) to support acting as /embed
* refactor some watch elements into new macros, and create a new 'embed.html'

**Comment by pExeen** [comment]
Hmm, I don't have that much experience with python but I'll give this a try. I'll try to find some time with uni and stuff, so it might take some time.
Thanks for the tips.

**Comment by user234683** [comment]
Best way to go about it is going to be a new /embed route, and then an embed.html which only has the video file. There isn't actually that much to copy from watch.html, just the video file html with the for loop that sets up the sources. The embed route would call the extract_info function in watch.py. If I have time after fixing some of the other things on my list I might try it, but that's going to be later in December.

**Comment by user234683** [comment]
This was a quick feature so I got it done. Current iteration is on the master branch. If you have any further suggestions for the embed page lemme know. Otherwise if you think it's good you can close the issue.

**Comment by Utopiah** [comment]
Nice, thanks for doing that!

1-liner for Tridactyl : `autocmd TabEnter * js Array.from(document.querySelectorAll('iframe[src*=youtube]')).map( v => { v.src = "http://localhost:9999/"+v.src } )`

It doesn't work everywhere but tried on a few pages and was a good start.
