### ISSUE TITLE
RFC: Most wanted bugfixes and features

### ISSUE THREAD

**Issue by user234683** [user234683/youtube-local#39]
I'll have some time mid-december to work more on youtube-local. Comment here with what bugfixes or features you think I should prioritize. If another comment suggests what you want, just add a thumbs up to it. I'm most interested in addressing things that are daily annoyances or that create friction, such as blocked exit nodes

**Comment by zrose584** [comment]
Sometimes `googlevideo.com/videoplayback` URLs fail with 503 error code.
Chrome's dev-console first says `(failed) net::ERR_CONTENT_LENGTH_MISMATCH`, and after retrying several times, either fails with 503 or succeeds with 206

I made screenshots:
* Here it succeeds after 3 (automated) retries:
![succeeds-after-3-retries](https://user-images.githubusercontent.com/57181548/100869651-3b9f5000-3495-11eb-9ccc-bd53a64bcb81.jpg)

* Here it first fails, but after a manual reload (ctrl+r) succeeds after 1 reload:
![succeeds-after-manual-reload](https://user-images.githubusercontent.com/57181548/100869669-3fcb6d80-3495-11eb-82b6-e086ad09053d.jpg)

This only happens on a subset of videos, but for these it's reproducible for several days (or longer).
It is reproducible with the URL extracted from: `youtube-dl -g -f 'mp4' 'https://www.youtube.com/watch?v=<id>`
I have following ideas:
* proxy videos, and make the proxy retry more than 3 times (con: increased latency)
* create fallback logic: mp4 -> webm -> different resolution -> hls
* Maybe it's enough to use webm as new default? (idk, haven't tested)

I send you a email with one of those videos, have you received it?

**Comment by user234683** [comment]
Yes I received it. Maybe my reply went into spam.

**Comment by zrose584** [comment]
No, there is no reply.. Even checked the settings: spam-filter is disabled.
Maybe try (yet) another mail-account?

**Comment by user234683** [comment]
I fixed my mailserver so it should show up now but regardless, I've opened an issue (#40 ) with the gist of my findings and to contain discussion for the 503 issue

**Comment by zrose584** [comment]
Another suggestion:
Ability to favor original (maybe auto generated) language captions over englisch.
So if there are captions "de (Automatic)" and "de (Automatic) -> en", it would favor the first one.
Basically I want english captions for english videos, and german captions for german videos, etc.

**Comment by zrose584** [comment]
FYI, I still haven't recived anything.

 
 

Gesendet: Mittwoch, 02. Dezember 2020 um 18:50 Uhr
Von: "James Taylor" <notifications@github.com>
An: "user234683/youtube-local" <youtube-local@noreply.github.com>
Cc: "zrose584" <zrose@gmx.net>, "Comment" <comment@noreply.github.com>
Betreff: Re: [user234683/youtube-local] RFC: Most wanted bugfixes and features (#39)


 

I fixed my mailserver so it should show up now but regardless, I've opened an issue (#40 ) with the gist of my findings and to contain discussion for the 503 issue
