### ISSUE TITLE
Change general design theme

### ISSUE THREAD

**Issue by arankaren** [user234683/youtube-local#41]
Hello could you integrate this commit where the [theme of all youtube-local is changed](https://libregit.org/heckyel/yt-local/commit/7a765dc664d20f966e4e52abac1f5372045e166c) 

Except the README.md

Please, this integration would be great

![Firefox_Screenshot_2020-12-15T05-46-21 060Z](https://user-images.githubusercontent.com/42627268/102176691-f9501880-3e6f-11eb-9aa6-25725a5297c6.png)

**Comment by user234683** [comment]
Are you still interested in this change? I was considering making it an optional css replacement. Would want to do css refactoring while I'm at it. But I'm prioritizing bug fixes and stability issues at the moment.

**Comment by canjbfeeltheesemuffins** [comment]
oh god no

if i wanted that i'd use the other fork
