### ISSUE TITLE
Double slashes get replaced with a single slash in some environments 

### ISSUE THREAD

**Issue by oktvn** [user234683/youtube-local#43]
Hello! I was testing this app on Google's Cloud Shell which runs web apps by proxying their ports to port 80 into a URL:

https://**8080**-8be694f9-38c9-4de2-8d54-cf17a257f2cd.europe-west4.cloudshell.dev/https://youtube.com

I noticed that double slashes get replaced with a single slash and I am not sure where the fault is -- Google or `youtube-local` 

![Screenshot_1](https://user-images.githubusercontent.com/29438749/102729492-38c7aa80-4331-11eb-83d8-084d2fe75175.png)

**Suggestion:** Can we skip the protocol part altogether in future versions as I don't think it's essential to the functioning of the app?

URLs without the protocol somewhat work, although no resources (images, videos) load.

![image](https://user-images.githubusercontent.com/29438749/102729534-614fa480-4331-11eb-9f98-9d8d0e85c74f.png)

Bunch of 404s in the console:

![image](https://user-images.githubusercontent.com/29438749/102729546-71678400-4331-11eb-8a68-4aeb9b34ce94.png)

**Comment by arankaren** [comment]
@oktvn, heckyel [solved this issue](https://libregit.org/heckyel/yt-local/commit/574cb2dae8534a8abba5710217e4f6c8655ff854) caused for env["PATH_INFO"] generated by uwsgi

**Comment by user234683** [comment]
Let me know if that fix works. I don't have a google shell environment to test it out with. Btw what server software is google shell using? Apache?

**Comment by arankaren** [comment]
https://github.com/user234683/youtube-local/commit/bf04570503c3afb5bc9e97a0df3cd2acc1d003af made by @user234683  work! :heart:
