### ISSUE TITLE
Responsive front-end

### ISSUE THREAD

**Issue by sorjgdojbodjhdo** [user234683/youtube-local#45]
Hi,

I recently discovered this app and so far it's been awesome. I recently tried to access it on my phone and noticed that the front-end was not mobile friendly at all.

I think it would great to add a bit of CSS/HTML code for the app to be responsive. 

Thank you for the app,

**Comment by arankaren** [comment]
@sorjgdojbodjhdo  maybe similar to https://github.com/user234683/youtube-local/issues/41

**Comment by prinixos** [comment]
Try my build of youtube local its not ready but its not ready but you can use it in a dark mode

**Comment by user234683** [comment]
Should now work down to 310px. I tested it on one mobile device, so let me know if there are any problems.

**Comment by canjbfeeltheesemuffins** [comment]
I hate the video resizes if theater mode is on. All I want is old YT video that was fixed. Normal was 360 or 480. Theater 720. [normal](https://assets.change.org/photos/7/kj/yb/qTKjYbuOOpZNBOb-800x450-noPad.jpg?1592343705) [theater](https://lh3.googleusercontent.com/YL9IUSdmbU8cT20LBdXm8Qms3Lbhyp-v2XEne3mw_6rNoBz6DnSq1g667qeBttu32wS-fGA1aqH3Ta2kWb6DDZMj=w640-h400-e365-rj-sc0x00ffffff)
