### ISSUE TITLE
Error: Error decrypting url signatures: Could not find player name 

### ISSUE THREAD

**Issue by brightersun99** [user234683/youtube-local#48]
Having problems playing THIS video on archlinux

using Error: Error decrypting url signatures: Could not find player name 

https://www.youtube.com/watch?v=gRhAPXJmm2c

if it matters, im using port 8081

hgeres error log from when it happens

127.0.0.1 - - [2021-02-02 08:18:48] "GET /https://r5---sn-hp57yne7.googlevideo.com/videoplayback?expire=1612293516&ei=LFEZYL7iIouUhwbJg7iAAw&ip=[XXX.XXX.XXX.XXX]&id=o-AMF7ULSizyPhQgnSrTKsYMDumgH_0nEQEUN-GYXRe4KB&itag=22&source=youtube&requiressl=yes&mh=iT&mm=31%2C29&mn=sn-hp57yne7%2Csn-hp57knz6&ms=au%2Crdu&mv=m&mvi=5&pl=16&gcr=us&initcwndbps=2151250&vprv=1&mime=video%2Fmp4&ns=FLcVac1YP6PtNfSRyfpg7o4F&cnr=14&ratebypass=yes&dur=245.968&lmt=1472212170500621&mt=1612271575&fvip=6&c=MWEB&n=qBikUebZeTGjxndqc&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cns%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIhALR1nfFLR0u-PJaJXkzFeVQbl3T5RuCpRGipTF1wffYBAiBdDKTXMVELLa5X03LqnrIdQMtNLKkIukEouAXYxiaM9A%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgLCJ0Qt6EyPrrcoRHiqtjouOYArO4vMND3OwBxbA3lrsCIQCmwKIAgLlVayqb3ghWVm-hYF1q4DX8B-vm5iBXBMtV5A%3D%3D HTTP/1.1" 206 47531332 10.450338
Retrieved comments     Latency: 0.757     Read time: 0.0
127.0.0.1 - - [2021-02-02 08:35:11] "GET /https://www.youtube.com/watch?v=-rUaC5G9uY8 HTTP/1.1" 200 86607 0.840325
Retrieved comments     Latency: 0.395     Read time: 0.004
127.0.0.1 - - [2021-02-02 08:35:25] "GET /https://www.youtube.com/watch?v=-rUaC5G9uY8 HTTP/1.1" 200 86782 0.688076
127.0.0.1 - - [2021-02-02 08:35:25] "GET /youtube.com/static/favicon.ico HTTP/1.1" 200 5979 0.000980

**Comment by brightersun99** [comment]
Some videos work, others do not. I do remember not having this issue last year, though.

**Comment by user234683** [comment]
Are you using the latest version? Also, the googlevideo urls contain the IP address so I edited it out for you.

If yes to latest version, then if you go to `~/.youtube-local/settings.txt` and change `debugging_save_responses` to `True`, then it will save all responses retrieved from YouYube into `~/.youtube-local/data/debug`. Then the next time the issue happens, upload the `watch` file and I can see what's wrong with it.

**Comment by arankaren** [comment]
It is solved with https://github.com/user234683/youtube-local/commit/d998fea9b970406b50ee22b1998a52a96bbd1a29
