### ISSUE TITLE
Running in Docker

### ISSUE THREAD

**Issue by megascrapper** [user234683/youtube-local#58]
I was trying to run youtube-local on Docker. While the container starts and there are some signs that the app is running internally, I couldn't access it through localhost:8080. I'm not quite sure if there's something I did wrong (I'm very new to docker) or it's just something from youtube-local itself.

Dockerfile:
``` dockerfile
FROM python:3.8-alpine
RUN apk add musl-dev build-base gcc libffi-dev python3-dev
COPY . .
RUN pip3 install -r requirements.txt
EXPOSE 8080
CMD ["python3", "server.py"]
```

Run commands : `docker run -dp 8080:8080 youtube-local`

**Comment by Utopiah** [comment]
I don't think it's anything specific to youtube-local but you can still try to see what went wrong by using docker logs or starting a bash shell in the container.

**Comment by megascrapper** [comment]
I tried rebuilding and now it works! The container has been running flawlessly for a few days now.
