### ISSUE TITLE
[Feature] Easily switch quality

### ISSUE THREAD

**Issue by Flam3rboy** [user234683/youtube-local#59]
As for now you can only choose and watch other video qualities if you click on download and the link.
It would be much more convenient if you can directly choose the quality on the video page itself, or atleast increase the default quality in the settings

**Comment by Utopiah** [comment]
I imagine it's related to `Video qualities other than 360p and 720p by muxing video and audio` in planned features. Namely that as-is higher resolution streams are actually re-using audio from lower resolution and are being remuxed on the fly which the in browser <video> player probably does not support. Consequently having to use another player while keeping both streams in sync is not trivial.

**Comment by user234683** [comment]
Update: I have a prototype of audio-video merging using Media Source Extensions that has working seeking, about 600 lines (vs 21k-60k with hls.js or dash.js). So it will be possible to get qualities other than 360p and 720p after cleaning it up, making it handle any edge cases or errors, and integrating it with a quality selector.

**Comment by Utopiah** [comment]
Neat, ready to test a dedicated branch if it helps.

**Comment by user234683** [comment]
The implementation of quality switching and audio-video merging is on master. The only outstanding issue I know of is that it doesn't yet delete from the buffered region ahead when handling QuotaExceededError (only deletes before, and even that is untested), so some long videos might fail in low memory conditions until I can reproduce that consistently.

**Comment by Utopiah** [comment]
Very nice. I didn't manage on a 3h video but a 30min video at 1080p 60fps worked fine, including random seeking.

**Comment by user234683** [comment]
QuotaExceededError is fixed, so long videos should work now. I also fixed it so it will include 4K video qualities as well. There's probably more tweaks to be made to av-merge in the future, but it's close enough to done for now. If you notice any bugs, a new issue can be opened for it

**Comment by arankaren** [comment]
Good feature. Please add WebM support. 

chromiun youtube-local not work.

```
Unsupported MIME type or codec:  audio/mp4; codecs="mp4a.40.2" video/mp4; codecs="av01.0.08M.08"
```

**Comment by user234683** [comment]
I can add webm support too. Might take some time though. That's odd that the codec doesn't work. I have the av1 codec working on ungoogled-chromium on debian buster. What OS, video id, and resolution are you using? Does H.264 (AVC) work? I pushed a commit that has a more specific error about what is not working. If the video (AV1) is the culprit rather than audio or missing MediaSource then there might be a package you need to install to support the AV1 codec required for 4K.

**Comment by arankaren** [comment]
ok @user234683 if adding WebM is very troublesome then don't add support. Yes on chromium with drivers to support mp4 it works fine. :+1:
