### ISSUE TITLE
Replace youtube URLs in description of videos with youtube-local URLs

### ISSUE THREAD

**Issue by AlexHasNoFace** [user234683/youtube-local#75]
In the description of a video open in youtube-local, any hyperlinks are displayed as is, even links to other YouTube videos. This means that clicking on one of these links will drag you into the actual YouTube frontend.
It would be nice to have the href changed so you stay on youtube-local.

**Comment by Utopiah** [comment]
Not exactly what you suggest but I use `autocmd BeforeRequest youtube.com js tri.excmds.urlmodify("-t", "youtube", "localtube")` for Tridactyl. This automatically converts a YT URL to a YTL one.
