### ISSUE TITLE
Cannot display comments

### ISSUE THREAD

**Issue by SlidingHorn** [user234683/youtube-local#78]
I don't know if maybe something didn't get pulled when I installed the requirements (a la #74 ), but when I try to view a video's comments, I get the following:

```
Traceback (most recent call last):
  File "/home/user/Downloads/youtube-local/youtube/comments.py", line 173, in video_comments
    post_process_comments_info(comments_info)
  File "/home/user/Downloads/youtube-local/youtube/comments.py", line 137, in post_process_comments_info
    comments_info['page_number'] = page_number = str(int(comments_info['offset']/20) + 1)
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
```

**Comment by user234683** [comment]
Make sure you have the latest version. YouTube disabled the old comments API recently.

**Comment by SlidingHorn** [comment]
Ah....switched to Arch the day before the release...I'll download here shortly and let you know if everything works (probably tomorrow - heading to bed shortly)

**Comment by SlidingHorn** [comment]
actually just updated - all good!

Closing now
