### ISSUE TITLE
Add webm opus support to avoid proprietary mp4 AAC codec

### ISSUE THREAD

**Issue by arankaren** [user234683/youtube-local#84]
This is possible?

In some O.S, I do not have proprietary codecs and use AV1 with Opus would be an option. what do you think?

```
Unsupported MIME type or codec:  audio/mp4; codecs="mp4a.40.2"
```
Thanks for your amazing work. @user234683 :1st_place_medal:

**Comment by user234683** [comment]
Yes, opus will be supported when webm support is added. I just need to find a good javascript library for parsing the webm EBML table. I [found this](https://github.com/suconghou/mediaparse/blob/master/src/ebml/ebml.ts) but I haven't tested it yet.
