### ISSUE TITLE
Why is the maximum FPS 25 on some videos?

### ISSUE THREAD

**Issue by DUOLabs333** [user234683/youtube-local#94]
Is there a hard technical limit why it can't be 30 or 60?

**Comment by DUOLabs333** [comment]
But check this video `http://localhost:8080/https://www.youtube.com/watch?v=JJyloRJ5Hzs`: while you can select a 60 fps option, it is noticeably more choppy than that.

**Comment by DUOLabs333** [comment]
Interestingly enough, Chrome actually plays it better than Firefox 88 (both on Arch Linux) -- it actually plays at 60 fps.

**Comment by DUOLabs333** [comment]
This may be because the VM can't take full advantage of the GPU.

**Comment by user234683** [comment]
I'm aware of the buffering issue; it's caused by high latency. I need to modify it to group segment requests in av-merge during high latency. But it sounds like the 60 fps thing is just a browser/os issue, yes?

**Comment by DUOLabs333** [comment]
Where is the downloading taking place (file-wise, I mean)?

**Comment by DUOLabs333** [comment]
No, I meant, which source file deal with the downloading?
