### ISSUE TITLE
Very slow video loading

### ISSUE THREAD

**Issue by zrose584** [user234683/youtube-local#95]
Even after waiting >1min not even the first segment gets loaded. I think doing a manual page reload helps, but even then one often has to wait ~10-20s for the first 10s (or so) to finally be loaded. After that, the playback often gets stale again. It's not really usable that way.. 

On the official frontend, the same video loads just fine (and nearly instantly).

I also noticed that sometimes the entire ~20min video gets loaded, even though I have paused it on 00:10. This seems wrong.

I saw this explanation: https://github.com/user234683/youtube-local/issues/94#issuecomment-940388240
But I wonder if that's all, why is there such latency in the first place? The official frontend doesn't seem to have it.

Also, even after I switch to "native player", the videos often take very long to load. (Both on chrome and on firefox, I think)

Are we really using the exact same requests as the normal frontend? Maybe we use some rarely used resource, and thus it's not cached on google's servers?

**Comment by DUOLabs333** [comment]
Looking at the Network tab, what seems to happen is that the next bit doesn't load until it reaches near the end, therefore the player has to wait. What would be better is that you continuously load more bits -- maybe always 30s out, without waiting for the current part to finish.

**Comment by DUOLabs333** [comment]
This can be seen when you pause the player -- instead of trying to load more, it just doesn't.

**Comment by DUOLabs333** [comment]
What user agent do you use now?

**Comment by e-edgren** [comment]
> Update: I found [this invidious issue](https://github.com/iv-org/invidious/issues/2194) and [this youtube-dl issue](https://github.com/ytdl-org/youtube-dl/issues/29326) recounting the same issue. It looks like invidious is solving it by using the Android client when requesting the URLs. I'll try to have a fix for it this weekend

That's great! I am looking forward to the update :)

> What user agent do you use now?

Who? Me? Firefox 93

**Comment by leimath** [comment]
When trying to load this video [Wendigoon's The American Broadcaster...](https://www.youtube.com/watch?v=eS1YssDSXBY). It does not load at all. Other videos work fine. Any comments on why/how I can fix this ?

**Comment by user234683** [comment]
Disable the "Prefer integrated sources" setting.See 
https://github.com/user234683/youtube-local/issues/129

**Comment by user234683** [comment]
Closing now that this has been fixed properly
