### ISSUE TITLE
Video does not resize, exceeds screen width on latest Chromium

### ISSUE THREAD

**Issue by DUOLabs333** [user234683/youtube-local#97]
On Firefox it is fine (at most, it takes up the width of the screen).

**Comment by DUOLabs333** [comment]
The problem with Chrome, is that it continues to scroll up, meaning you have to scroll down. I realized that this is due to my zoom level. Interesting that this problem doesn't happen on Firefox (mostly because it scales well, without me having me to zoom in).

**Comment by DUOLabs333** [comment]
I also found that on Chrome, no text shows (no problem on Firefox).

**Comment by canjbfeeltheesemuffins** [comment]
> Incidentally enough, it also helped the framerate in Firefox a lot -- not completely, but much better.

ye the bigger the video view the more cpu
